import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers  from "./components/Providers";
import Appbar from "./components/Appbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TuneChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <Providers>
          <Appbar />
          {children}
        </Providers>
        </body>
    </html>
  );
}
